stages:
    - build
    - test
    - deploy

build:
    services:
        - hub.hamdocker.ir/docker:dind
    tags:
        - bootcamp
        - fi
    stage: build
    image: hub.hamdocker.ir/docker:dind
    script:
        - mkdir -p $HOME/.docker && cat "$DOCKER_AUTH_CONFIG" > $HOME/.docker/config.json
        - docker build -t registry.hamdocker.ir/torob-bootcamp-1402/chahkandi-chatbot:${CI_COMMIT_SHORT_SHA} .
        - docker push registry.hamdocker.ir/torob-bootcamp-1402/chahkandi-chatbot:${CI_COMMIT_SHORT_SHA}

test:
    tags:
        - bootcamp
        - fi
    stage: test
    script:
        - pip install -r requirements.txt
        - python manage.py test

deploy:
    tags:
        - bootcamp
        - ir
    stage: deploy
    image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
    only:
        refs:
        - main
    script:
        - darkube deploy --token ${DEPLOY_TOKEN} --app-id ${APP_ID} --image-tag ${CI_COMMIT_SHORT_SHA}