stages:
    - build
    - test
    - deploy

build:
    services:
        - name: docker.arvancloud.ir/docker:dind
          entrypoint: ["env", "-u", "DOCKER_HOST"]
          command: ["dockerd-entrypoint.sh"]
          alias: docker.arvancloud.ir
    variables:
        DOCKER_HOST: tcp://docker.arvancloud.ir:2375/
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ""
    tags:
        - bootcamp
        - ir
    stage: build
    image: docker.arvancloud.ir/docker:stable
    script:
        - mkdir -p $HOME/.docker && cat "$DOCKER_AUTH_CONFIG" > $HOME/.docker/config.json
        - docker build -t registry.hamdocker.ir/torob-bootcamp-1402/chahkandi-chatbot:${CI_COMMIT_SHORT_SHA} .
        - docker push registry.hamdocker.ir/torob-bootcamp-1402/chahkandi-chatbot:${CI_COMMIT_SHORT_SHA}

test:
    tags:
        - bootcamp
        - fi
    stage: test
    script:
        - echo test

deploy:
    tags:
        - bootcamp
        - ir
    stage: deploy
    image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
    only:
        refs:
        - main
    script:
        - darkube deploy --token ${DEPLOY_TOKEN} --app-id ${APP_ID} --image-tag ${CI_COMMIT_SHORT_SHA}

