# Generated by Django 4.2.7 on 2023-11-26 13:53

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='vector',
            field=django.contrib.postgres.search.SearchVectorField(default=None),
        ),
        migrations.AddField(
            model_name='message',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(default=None),
        ),
    ]
