# Generated by Django 4.2.7 on 2023-11-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chat_vector_message_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='system_prompt',
            field=models.CharField(default='Based on the specific data: {data}, answer to the following question.'),
        ),
    ]
