# Generated by Django 4.2.7 on 2023-11-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatbot_system_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='vector',
        ),
    ]
