# Generated by Django 4.2.7 on 2023-11-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_message_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chatbot_response',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_message',
            field=models.CharField(max_length=4096),
        ),
    ]
