# Generated by Django 4.2.7 on 2023-11-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_message_chatbot_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_history',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_message',
            field=models.CharField(max_length=1024),
        ),
    ]
