# Generated by Django 4.2.7 on 2023-11-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_chat_chat_history_alter_message_user_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
