# Generated by Django 4.2.7 on 2023-11-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
    ]
